apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.api.name }}-clusterip"
spec:
  type: ClusterIP
  selector:
    environment: {{ .Values.api.environment }}
  ports:
  - port: {{ .Values.api.port }}
    protocol: TCP