apiVersion: v1 
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-clusterip
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.postgres.component }}
  ports:
    - port: {{ .Values.postgres.port }}
      protocol: TCP