apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.converter.name }}-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.converter.port }}
    protocol: TCP
  selector:
    part: {{ .Values.converter.part }}