apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2NvbnY6Y29udkBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvY29udg==
  AMQP_EXCHANGE: amex
  AMQP_USER: conv
  AMQP_PASSWORD: conv
  AMQP_HOSTNAME: conv